### ISSUE TITLE
No License Specified

### ISSUE THREAD

**Issue by RKdev** [coreos/awscli#10]
Hi!

I would like to use your docker file as a starting point for my own container project, but you don't have a licensed file specified in the repo. Technically this means that the files fall under default copyright and are not legal for others to use. Is this meant to be an open source project?

**Comment by pieterlange** [comment]
Pretty sure it is. @colhom maybe add a MIT license file?

**Comment by colhom** [comment]
\cc @philips

**Comment by euank** [comment]
Fixed by #14, thanks for the reminder!
