### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by whereisaaron** [coreos/awscli#13]
Is this project/image still alive? The awscli included is about 18 months out of date (still defaults to V2 auth) and there are pull requests #9 and #12 to update it from 7 and 3 months ago by @euank and @martinssipenko update the versions with no movement.

Is this still a going concern or better to fork or switch to a different image?

**Comment by euank** [comment]
Apologies for not responding sooner and for the slow movement this repo has seen.
I added a team to explicitly own this repository, so hopefully it shouldn't be so neglected again.

To answer the question: yes this repository is alive.
Let me know if you have other questions or concerns.
