### ISSUE TITLE
quay.io/coreos/awscli:master broken: "awscli[6]: /bin/sh: can't open 'aws'"

### ISSUE THREAD

**Issue by ankon** [coreos/awscli#15]
As part of my kube-aws setup I'm running on CoreOS 1235.12.0 (yes, I know it's old, different construction site!), and the follow command in the cloudinit script started producing errors:

```sh 
/usr/bin/rkt run \
   --net=host \
   --volume=dns,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=dns,target=/etc/resolv.conf  \
   --volume=awsenv,kind=host,source=/var/run/coreos,readOnly=false --mount volume=awsenv,target=/var/run/coreos \
   --trust-keys-from-https \
   quay.io/coreos/awscli:master -- aws s3 --region $REGION  cp s3://xxxxxxxxxxxxxxxx/$USERDATA_FILE /var/run/coreos/
```

This breaks the complete startup of the instance, as the next command then of course won't work either:
```sh
exec /usr/bin/coreos-cloudinit --from-file /var/run/coreos/$USERDATA_FILE
```

I can reproduce this minimally with this:
```sh
$ sudo /usr/bin/rkt run --net=host --volume=dns,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=dns,target=/etc/resolv.conf --volume=awsenv,kind=host,source=/var/run/coreos,readOnly=false --mount volume=awsenv,target=/var/run/coreos --trust-keys-from-https quay.io/coreos/awscli:master -- aws
[  644.410459] awscli[6]: /bin/sh: can't open 'aws'
```

It still works with the 'latest' version, which is actually from a year ago:
```sh
$ sudo /usr/bin/rkt run --net=host --volume=dns,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=dns,target=/etc/resolv.conf --volume=awsenv,kind=host,source=/var/run/coreos,readOnly=false --mount volume=awsenv,target=/var/run/coreos --trust-keys-from-https quay.io/coreos/awscli:latest -- aws
[ 1640.167349] awscli[6]: usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
[ 1640.167910] awscli[6]: To see help text, you can run:
[ 1640.168309] awscli[6]:   aws help
[ 1640.168631] awscli[6]:   aws <command> help
[ 1640.168957] awscli[6]:   aws <command> <subcommand> help
[ 1640.169282] awscli[6]: aws: error: too few arguments
```

`rkt image list` gives:
~~~~
ID			NAME					SIZE	IMPORT TIME	LAST USED
sha512-8b46b029b1f8	quay.io/coreos/awscli:master		197MiB	38 minutes ago	38 minutes ago
sha512-1ffd0864313d	quay.io/coreos/awscli:latest		196MiB	45 seconds ago	44 seconds ago
~~~~

**Comment by ankon** [comment]
I noticed on quay.io/coreos/awscli that the 'master' image now has a 'CMD' in the Dockerfile, but I cannot see where this actually comes from.

Master:
![screen-quay-master](https://user-images.githubusercontent.com/1210641/35108378-aff8422a-fc73-11e7-9441-93e0ae8ef6f6.png)

Latest:
![screen-quay-latest](https://user-images.githubusercontent.com/1210641/35108385-b6994fe8-fc73-11e7-9963-4fc326d8db5c.png)

**Comment by euank** [comment]
The `CMD /bin/sh` comes from this change in alpine: https://github.com/gliderlabs/docker-alpine/pull/199

The `FROM alpine` is implicitly including that if a new enough alpine image is referenced.

We can fix this by explicitly overriding cmd to be `/bin/sh -c` to match the previous behavior.

It can also be worked around by using either of the following commands:

```
/usr/bin/rkt run  ..... quay.io/coreos/awscli:latest --exec=aws -- s3 ....

# or

/usr/bin/rkt run  ..... quay.io/coreos/awscli:latest --exec=sh -- -c "aws s3 ...."
```

**Comment by ankon** [comment]
For now I worked around this by using :latest, which right now seems to be "previous". It would be great to have versions on this repository, so that one can point to the specific images.

Right now I need to recover my complete kubernetes cluster, as the attempt to fix this problem ("cannot bring up new nodes") created some major mess due to some critical other commands failing. I think it would be best to restore the previous behavior for now, under the assumption that this might have actually affected more people, and the change being an "API change" for awscli:master, if you will :)

**Comment by pieterlange** [comment]
I'm in the same boat with an old cluster that needs upgrading, but it looks like the current kube-aws behaviour would also trigger this.

https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cluster.yaml#L964

**Comment by pieterlange** [comment]
So, i know it's bad to depend on "latest" / "master" unversioned image tags but this has been kube-aws's dependency since it's inception and may potentially hit every kube-aws deployed cluster. Can we restore previous behaviour on `master` for now @euank and give users some time to update their clusters?

**Comment by mumoshu** [comment]
cc'ing @Fsero @danielfm @c-knowles @camilb @whereisaaron

In case your node starts failing while fetching cloud-configs from s3, this issue would help. `awsCliImage.tag` to [something older](https://quay.io/repository/coreos/awscli?tab=tags) or override the aws command in `cloud-config-*` as @ankon suggested.

**Comment by Fsero** [comment]
Thanks for pointing this out @mumoshu , we have pinned versions and setup a internal docker registry after quay.io was down and now we fetch new versions from quay or gcr to keep synched.

**Comment by whereisaaron** [comment]
Thanks @mumoshu. We should warn `kube-aws` users to check their etcd nodes ASAP. Versions of `kube-aws` from ~~at least 0.9.3~~ 0.9.5-rc.5 and earlier deployed `etcd` with the `etcd-lock` reboot strategy. Given this issue, it appears the next automatic update reboot could bring down everyone's k8s etcd cluster without notice? The current 0.9.5 and later versions appears safe ('reboot-strategy: "off"') by default. ~~Not sure about 0.9.4/5/6/7/8?~~

It looks like this was [fixed on March 20](https://github.com/kubernetes-incubator/kube-aws/commit/ea89628de15b76f3c8897422fc2de64cdcd39826) for version v0.9.5-rc.5 and later, changing the etcd node strategy to 'off'. So any cluster older than ~9 months is ripe for sudden etcd failure.

@ankon sorry you got to be the canary!

This is obviously a hard lesson in using versioned tags! To be fair though, `coreos/awscli` doesn't actually have any tagged versions. Only `master`, `latest`, and `edge` (or is that big hex string a 'version'?). Could we now tag the old ('latest') version and this new version with a versioned tag?

Given the purpose of this container is purely to provide `aws` could we tag the old and new versions with the awscli version it contains? Then current and future clusters can be tagged to one of these versions, and we won't have this 'cluster apocalypse' again with the next breaking change :-).

![image](https://user-images.githubusercontent.com/1109585/35285471-75b6bfcc-002b-11e8-9ead-b4fc8b9cd70e.png)

**Comment by ankon** [comment]
> Versions of kube-aws from at least 0.9.7 and earlier deployed etcd with the etcd-lock reboot strategy.

Just had a minor heart-attack, that was a good pointer to check!

At least on my (horribly old kube-aws 0.9.4-ish) cluster it seems that this etcd is indeed configured to use the 'etcd-lock' reboot strategy, BUT locksmithd complains about a missing "reboot window", and so the reboot doesn't actually happen. I'm in the progress of replacing this cluster, so right now things seem to be ok ... for me.

> Given the purpose of this container is purely to provide aws could we tag the old and new versions with the awscli version it contains? 

This seems reasonable to me, there doesn't seem to be much of a point to use an arbitrary AWS CLI version when the actual needed parts are known in advance (copy stuff from S3, something else? :D).

**Comment by whereisaaron** [comment]
Maybe @ankon, but I suggest change it to 'off' to be sure. I had an old 0.9.3 etcd reboot even with the 'etcd-lock' errors. It appeared to be for updates, but maybe it was for a different reason.

**Comment by euank** [comment]
Thanks to @pieterlange for the PR to fix this problem on master. That change should be built/published now, so this issue should be fixed.

Ideally the `master/edge/latest` mutable tags wouldn't be the way these images are consumed, but I think discussion of these tags belongs in a different issue.

Thanks for reporting the issue
